development:
  clients:
    default:
      uri: mongodb+srv://csacchi:0POUbtiI5kRJU4Zu@bricksnackcluster-uylch.mongodb.net/bricksnack_development?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
test:
  clients:
    default:
      uri: mongodb+srv://csacchi:0POUbtiI5kRJU4Zu@bricksnackcluster-uylch.mongodb.net/bricksnack_test?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
production:
  clients:
    default:
      uri: mongodb+srv://csacchi:0POUbtiI5kRJU4Zu@bricksnackcluster-uylch.mongodb.net/bricksnack_production?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
